/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_acceuil (void)
{
  GtkWidget *acceuil;
  GtkWidget *fixed1;
  GtkWidget *button1;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label1;
  GtkWidget *button2;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label2;

  acceuil = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (acceuil, 1000, 800);
  gtk_window_set_title (GTK_WINDOW (acceuil), _("acceuil"));
  gtk_window_set_position (GTK_WINDOW (acceuil), GTK_WIN_POS_CENTER);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (acceuil), fixed1);

  button1 = gtk_button_new ();
  gtk_widget_show (button1);
  gtk_fixed_put (GTK_FIXED (fixed1), button1, 808, 688);
  gtk_widget_set_size_request (button1, 136, 61);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (button1), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label1 = gtk_label_new_with_mnemonic (_("Quitter"));
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (hbox1), label1, FALSE, FALSE, 0);

  button2 = gtk_button_new ();
  gtk_widget_show (button2);
  gtk_fixed_put (GTK_FIXED (fixed1), button2, 376, 352);
  gtk_widget_set_size_request (button2, 208, 62);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (button2), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-execute", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label2 = gtk_label_new_with_mnemonic (_("Gestion  Troupeaux"));
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (hbox2), label2, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button1, "clicked",
                    G_CALLBACK (gtk_main_quit),
                    NULL);
  g_signal_connect ((gpointer) button2, "clicked",
                    G_CALLBACK (on_AcceuilGestion_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (acceuil, acceuil, "acceuil");
  GLADE_HOOKUP_OBJECT (acceuil, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (acceuil, button1, "button1");
  GLADE_HOOKUP_OBJECT (acceuil, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (acceuil, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (acceuil, image1, "image1");
  GLADE_HOOKUP_OBJECT (acceuil, label1, "label1");
  GLADE_HOOKUP_OBJECT (acceuil, button2, "button2");
  GLADE_HOOKUP_OBJECT (acceuil, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (acceuil, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (acceuil, image2, "image2");
  GLADE_HOOKUP_OBJECT (acceuil, label2, "label2");

  return acceuil;
}

GtkWidget*
create_gestion (void)
{
  GtkWidget *gestion;
  GtkWidget *fixed2;
  GtkWidget *button7;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label32;
  GtkWidget *button8;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label33;
  GtkWidget *notebook1;
  GtkWidget *fixed3;
  GtkWidget *entry1;
  GtkWidget *entry2;
  GtkWidget *entry3;
  GtkWidget *entry4;
  GtkWidget *entry5;
  GtkWidget *label3;
  GtkWidget *label10;
  GtkWidget *label8;
  GtkWidget *label35;
  GtkWidget *label34;
  GtkWidget *label11;
  GtkWidget *label12;
  GtkWidget *label13;
  GtkWidget *label6;
  GtkWidget *label7;
  GtkWidget *label4;
  GtkWidget *label9;
  GtkWidget *button3;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label14;
  GtkWidget *label5;
  GtkWidget *label15;
  GtkWidget *fixed4;
  GtkWidget *entry6;
  GtkWidget *entry7;
  GtkWidget *entry8;
  GtkWidget *entry9;
  GtkWidget *label20;
  GtkWidget *label18;
  GtkWidget *label16;
  GtkWidget *label37;
  GtkWidget *label36;
  GtkWidget *label19;
  GtkWidget *label17;
  GtkWidget *button4;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label21;
  GtkWidget *label22;
  GtkWidget *fixed6;
  GtkWidget *scrolledwindow2;
  GtkWidget *treeview2;
  GtkWidget *entry10;
  GtkWidget *bmodifier;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image14;
  GtkWidget *label49;
  GtkWidget *bafficher12;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image16;
  GtkWidget *label51;
  GtkWidget *label27;
  GtkWidget *label26;
  GtkWidget *bsupprimer;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image15;
  GtkWidget *label50;
  GtkWidget *button6;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label30;
  GtkWidget *label28;
  GtkWidget *label29;
  GtkWidget *label31;

  gestion = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (gestion, 1000, 800);
  gtk_window_set_title (GTK_WINDOW (gestion), _("gestion Troupeaux"));
  gtk_window_set_position (GTK_WINDOW (gestion), GTK_WIN_POS_CENTER);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (gestion), fixed2);

  button7 = gtk_button_new ();
  gtk_widget_show (button7);
  gtk_fixed_put (GTK_FIXED (fixed2), button7, 912, 8);
  gtk_widget_set_size_request (button7, 80, 48);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (button7), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label32 = gtk_label_new_with_mnemonic (_("<span foreground=\"red\"><b>Quitter</b></span>"));
  gtk_widget_show (label32);
  gtk_box_pack_start (GTK_BOX (hbox7), label32, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label32), TRUE);

  button8 = gtk_button_new ();
  gtk_widget_show (button8);
  gtk_fixed_put (GTK_FIXED (fixed2), button8, 824, 8);
  gtk_widget_set_size_request (button8, 80, 48);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (button8), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label33 = gtk_label_new_with_mnemonic (_("<span foreground=\"green\"><b>Retour</b></span>"));
  gtk_widget_show (label33);
  gtk_box_pack_start (GTK_BOX (hbox8), label33, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label33), TRUE);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_fixed_put (GTK_FIXED (fixed2), notebook1, 0, 56);
  gtk_widget_set_size_request (notebook1, 1000, 768);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed3);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed3), entry1, 184, 176);
  gtk_widget_set_size_request (entry1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (fixed3), entry2, 184, 232);
  gtk_widget_set_size_request (entry2, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2), 8226);

  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_fixed_put (GTK_FIXED (fixed3), entry3, 184, 344);
  gtk_widget_set_size_request (entry3, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3), 8226);

  entry4 = gtk_entry_new ();
  gtk_widget_show (entry4);
  gtk_fixed_put (GTK_FIXED (fixed3), entry4, 184, 288);
  gtk_widget_set_size_request (entry4, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4), 8226);

  entry5 = gtk_entry_new ();
  gtk_widget_show (entry5);
  gtk_fixed_put (GTK_FIXED (fixed3), entry5, 184, 120);
  gtk_widget_set_size_request (entry5, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry5), 8226);

  label3 = gtk_label_new (_("Prix : "));
  gtk_widget_show (label3);
  gtk_fixed_put (GTK_FIXED (fixed3), label3, 88, 336);
  gtk_widget_set_size_request (label3, 104, 48);

  label10 = gtk_label_new (_("<span foreground=\"black\" ><b>Saisir Prix !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed3), label10, 352, 328);
  gtk_widget_set_size_request (label10, 216, 64);
  gtk_label_set_use_markup (GTK_LABEL (label10), TRUE);

  label8 = gtk_label_new (_("<span foreground=\"black\" ><b>Saisir type !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed3), label8, 352, 216);
  gtk_widget_set_size_request (label8, 216, 64);
  gtk_label_set_use_markup (GTK_LABEL (label8), TRUE);

  label35 = gtk_label_new (_("<span foreground=\"blue\" ><b> Troupeaux ajout\303\251 avec succes !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed3), label35, 0, 0);
  gtk_widget_set_size_request (label35, 264, 56);
  gtk_label_set_use_markup (GTK_LABEL (label35), TRUE);

  label34 = gtk_label_new (_("<span foreground=\"black\" ><b> troupeaux  existant !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed3), label34, 184, 24);
  gtk_widget_set_size_request (label34, 216, 64);
  gtk_label_set_use_markup (GTK_LABEL (label34), TRUE);

  label11 = gtk_label_new (_("<span foreground=\"black\" ><b>Ajouter troupeaux :</b></span>"));
  gtk_widget_show (label11);
  gtk_fixed_put (GTK_FIXED (fixed3), label11, 336, 48);
  gtk_widget_set_size_request (label11, 216, 64);
  gtk_label_set_use_markup (GTK_LABEL (label11), TRUE);

  label12 = gtk_label_new (_("ID : "));
  gtk_widget_show (label12);
  gtk_fixed_put (GTK_FIXED (fixed3), label12, 88, 112);
  gtk_widget_set_size_request (label12, 104, 48);

  label13 = gtk_label_new (_("<span foreground=\"black\" ><b>Saisir ID !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed3), label13, 384, 112);
  gtk_widget_set_size_request (label13, 128, 40);
  gtk_label_set_use_markup (GTK_LABEL (label13), TRUE);

  label6 = gtk_label_new (_("Sexe : "));
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed3), label6, 88, 168);
  gtk_widget_set_size_request (label6, 104, 48);

  label7 = gtk_label_new (_("<span foreground=\"black\" ><b>Saisir Sexe !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed3), label7, 344, 152);
  gtk_widget_set_size_request (label7, 216, 64);
  gtk_label_set_use_markup (GTK_LABEL (label7), TRUE);

  label4 = gtk_label_new (_("Date: "));
  gtk_widget_show (label4);
  gtk_fixed_put (GTK_FIXED (fixed3), label4, 88, 280);
  gtk_widget_set_size_request (label4, 104, 48);

  label9 = gtk_label_new (_("<span foreground=\"black\" ><b>Saisir date!</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed3), label9, 352, 272);
  gtk_widget_set_size_request (label9, 216, 64);
  gtk_label_set_use_markup (GTK_LABEL (label9), TRUE);

  button3 = gtk_button_new ();
  gtk_widget_show (button3);
  gtk_fixed_put (GTK_FIXED (fixed3), button3, 200, 432);
  gtk_widget_set_size_request (button3, 128, 56);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button3), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label14 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label14);
  gtk_box_pack_start (GTK_BOX (hbox3), label14, FALSE, FALSE, 0);

  label5 = gtk_label_new (_("Type : "));
  gtk_widget_show (label5);
  gtk_fixed_put (GTK_FIXED (fixed3), label5, 88, 224);
  gtk_widget_set_size_request (label5, 104, 48);

  label15 = gtk_label_new (_("<span foreground=\"purple\"><b>Ajouter</b></span>"));
  gtk_widget_show (label15);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label15);
  gtk_label_set_use_markup (GTK_LABEL (label15), TRUE);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed4);

  entry6 = gtk_entry_new ();
  gtk_widget_show (entry6);
  gtk_fixed_put (GTK_FIXED (fixed4), entry6, 184, 176);
  gtk_widget_set_size_request (entry6, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry6), 8226);

  entry7 = gtk_entry_new ();
  gtk_widget_show (entry7);
  gtk_fixed_put (GTK_FIXED (fixed4), entry7, 184, 232);
  gtk_widget_set_size_request (entry7, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry7), 8226);

  entry8 = gtk_entry_new ();
  gtk_widget_show (entry8);
  gtk_fixed_put (GTK_FIXED (fixed4), entry8, 184, 344);
  gtk_widget_set_size_request (entry8, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry8), 8226);

  entry9 = gtk_entry_new ();
  gtk_widget_show (entry9);
  gtk_fixed_put (GTK_FIXED (fixed4), entry9, 184, 288);
  gtk_widget_set_size_request (entry9, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry9), 8226);

  label20 = gtk_label_new ("");
  gtk_widget_show (label20);
  gtk_fixed_put (GTK_FIXED (fixed4), label20, 248, 48);
  gtk_widget_set_size_request (label20, 56, 48);

  label18 = gtk_label_new (_("Type : "));
  gtk_widget_show (label18);
  gtk_fixed_put (GTK_FIXED (fixed4), label18, 88, 224);
  gtk_widget_set_size_request (label18, 104, 48);

  label16 = gtk_label_new (_("Prix: "));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed4), label16, 88, 336);
  gtk_widget_set_size_request (label16, 104, 48);

  label37 = gtk_label_new (_("<span foreground=\"green\" ><b>Troupeaux Modifi\303\251 avec succes </b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed4), label37, 104, 0);
  gtk_widget_set_size_request (label37, 296, 56);
  gtk_label_set_use_markup (GTK_LABEL (label37), TRUE);

  label36 = gtk_label_new (_("<span foreground=\"black\" ><b>Modifier troupeaux de ID :</b></span>"));
  gtk_widget_show (label36);
  gtk_fixed_put (GTK_FIXED (fixed4), label36, 40, 40);
  gtk_widget_set_size_request (label36, 216, 64);
  gtk_label_set_use_markup (GTK_LABEL (label36), TRUE);

  label19 = gtk_label_new (_("Sexe : "));
  gtk_widget_show (label19);
  gtk_fixed_put (GTK_FIXED (fixed4), label19, 88, 168);
  gtk_widget_set_size_request (label19, 104, 48);

  label17 = gtk_label_new (_("Date : "));
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed4), label17, 88, 272);
  gtk_widget_set_size_request (label17, 104, 48);

  button4 = gtk_button_new ();
  gtk_fixed_put (GTK_FIXED (fixed4), button4, 168, 432);
  gtk_widget_set_size_request (button4, 128, 56);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button4), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-index", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label21 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label21);
  gtk_box_pack_start (GTK_BOX (hbox4), label21, FALSE, FALSE, 0);

  label22 = gtk_label_new (_("<span foreground=\"purple\"><b>Modifier</b></span>"));
  gtk_widget_show (label22);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label22);
  gtk_label_set_use_markup (GTK_LABEL (label22), TRUE);

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed6);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow2);
  gtk_fixed_put (GTK_FIXED (fixed6), scrolledwindow2, 8, 80);
  gtk_widget_set_size_request (scrolledwindow2, 592, 456);

  treeview2 = gtk_tree_view_new ();
  gtk_widget_show (treeview2);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), treeview2);
  gtk_widget_set_size_request (treeview2, 592, 456);

  entry10 = gtk_entry_new ();
  gtk_widget_show (entry10);
  gtk_fixed_put (GTK_FIXED (fixed6), entry10, 688, 160);
  gtk_widget_set_size_request (entry10, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry10), 8226);

  bmodifier = gtk_button_new ();
  gtk_widget_show (bmodifier);
  gtk_fixed_put (GTK_FIXED (fixed6), bmodifier, 872, 288);
  gtk_widget_set_size_request (bmodifier, 112, 48);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (bmodifier), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image14 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox14), image14, FALSE, FALSE, 0);

  label49 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label49);
  gtk_box_pack_start (GTK_BOX (hbox14), label49, FALSE, FALSE, 0);

  bafficher12 = gtk_button_new ();
  gtk_widget_show (bafficher12);
  gtk_fixed_put (GTK_FIXED (fixed6), bafficher12, 872, 448);
  gtk_widget_set_size_request (bafficher12, 112, 48);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (bafficher12), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image16 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox16), image16, FALSE, FALSE, 0);

  label51 = gtk_label_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (label51);
  gtk_box_pack_start (GTK_BOX (hbox16), label51, FALSE, FALSE, 0);

  label27 = gtk_label_new ("");
  gtk_widget_show (label27);
  gtk_fixed_put (GTK_FIXED (fixed6), label27, 720, 208);
  gtk_widget_set_size_request (label27, 48, 56);

  label26 = gtk_label_new (_("<span foreground=\"blue\" ><b>Resultat(s) obtenu(s)</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed6), label26, 784, 200);
  gtk_widget_set_size_request (label26, 216, 72);
  gtk_label_set_use_markup (GTK_LABEL (label26), TRUE);

  bsupprimer = gtk_button_new ();
  gtk_widget_show (bsupprimer);
  gtk_fixed_put (GTK_FIXED (fixed6), bsupprimer, 872, 368);
  gtk_widget_set_size_request (bsupprimer, 112, 48);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (bsupprimer), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image15 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox15), image15, FALSE, FALSE, 0);

  label50 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label50);
  gtk_box_pack_start (GTK_BOX (hbox15), label50, FALSE, FALSE, 0);

  button6 = gtk_button_new ();
  gtk_widget_show (button6);
  gtk_fixed_put (GTK_FIXED (fixed6), button6, 872, 152);
  gtk_widget_set_size_request (button6, 112, 48);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (button6), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label30 = gtk_label_new_with_mnemonic (_("Chercher"));
  gtk_widget_show (label30);
  gtk_box_pack_start (GTK_BOX (hbox6), label30, FALSE, FALSE, 0);

  label28 = gtk_label_new (_("<span foreground=\"black\" ><b>Saisir ID !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed6), label28, 704, 64);
  gtk_widget_set_size_request (label28, 216, 64);
  gtk_label_set_use_markup (GTK_LABEL (label28), TRUE);

  label29 = gtk_label_new (_("Id : "));
  gtk_widget_show (label29);
  gtk_fixed_put (GTK_FIXED (fixed6), label29, 592, 152);
  gtk_widget_set_size_request (label29, 112, 48);

  label31 = gtk_label_new (_("<span foreground=\"purple\"><b>Rechercher-Afficher-Supprimer</b></span>"));
  gtk_widget_show (label31);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), label31);
  gtk_label_set_use_markup (GTK_LABEL (label31), TRUE);

  g_signal_connect ((gpointer) button7, "clicked",
                    G_CALLBACK (gtk_main_quit),
                    NULL);
  g_signal_connect ((gpointer) button8, "clicked",
                    G_CALLBACK (on_GestionAcceuil_clicked),
                    NULL);
  g_signal_connect ((gpointer) button3, "clicked",
                    G_CALLBACK (on_Ajoutertroupeaux_clicked),
                    NULL);
  g_signal_connect ((gpointer) button4, "clicked",
                    G_CALLBACK (on_Modifiertroupeaux_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeview2, "row_activated",
                    G_CALLBACK (on_treeview2_row_activated),
                    NULL);
  g_signal_connect ((gpointer) bmodifier, "clicked",
                    G_CALLBACK (on_bmodifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) bafficher12, "clicked",
                    G_CALLBACK (on_bafficher12_clicked),
                    NULL);
  g_signal_connect ((gpointer) bsupprimer, "clicked",
                    G_CALLBACK (on_bsupprimer_clicked),
                    NULL);
  g_signal_connect ((gpointer) button6, "clicked",
                    G_CALLBACK (on_cherchertroupeaux_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (gestion, gestion, "gestion");
  GLADE_HOOKUP_OBJECT (gestion, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (gestion, button7, "button7");
  GLADE_HOOKUP_OBJECT (gestion, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (gestion, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (gestion, image7, "image7");
  GLADE_HOOKUP_OBJECT (gestion, label32, "label32");
  GLADE_HOOKUP_OBJECT (gestion, button8, "button8");
  GLADE_HOOKUP_OBJECT (gestion, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (gestion, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (gestion, image8, "image8");
  GLADE_HOOKUP_OBJECT (gestion, label33, "label33");
  GLADE_HOOKUP_OBJECT (gestion, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (gestion, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (gestion, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (gestion, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (gestion, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (gestion, entry4, "entry4");
  GLADE_HOOKUP_OBJECT (gestion, entry5, "entry5");
  GLADE_HOOKUP_OBJECT (gestion, label3, "label3");
  GLADE_HOOKUP_OBJECT (gestion, label10, "label10");
  GLADE_HOOKUP_OBJECT (gestion, label8, "label8");
  GLADE_HOOKUP_OBJECT (gestion, label35, "label35");
  GLADE_HOOKUP_OBJECT (gestion, label34, "label34");
  GLADE_HOOKUP_OBJECT (gestion, label11, "label11");
  GLADE_HOOKUP_OBJECT (gestion, label12, "label12");
  GLADE_HOOKUP_OBJECT (gestion, label13, "label13");
  GLADE_HOOKUP_OBJECT (gestion, label6, "label6");
  GLADE_HOOKUP_OBJECT (gestion, label7, "label7");
  GLADE_HOOKUP_OBJECT (gestion, label4, "label4");
  GLADE_HOOKUP_OBJECT (gestion, label9, "label9");
  GLADE_HOOKUP_OBJECT (gestion, button3, "button3");
  GLADE_HOOKUP_OBJECT (gestion, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (gestion, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (gestion, image3, "image3");
  GLADE_HOOKUP_OBJECT (gestion, label14, "label14");
  GLADE_HOOKUP_OBJECT (gestion, label5, "label5");
  GLADE_HOOKUP_OBJECT (gestion, label15, "label15");
  GLADE_HOOKUP_OBJECT (gestion, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (gestion, entry6, "entry6");
  GLADE_HOOKUP_OBJECT (gestion, entry7, "entry7");
  GLADE_HOOKUP_OBJECT (gestion, entry8, "entry8");
  GLADE_HOOKUP_OBJECT (gestion, entry9, "entry9");
  GLADE_HOOKUP_OBJECT (gestion, label20, "label20");
  GLADE_HOOKUP_OBJECT (gestion, label18, "label18");
  GLADE_HOOKUP_OBJECT (gestion, label16, "label16");
  GLADE_HOOKUP_OBJECT (gestion, label37, "label37");
  GLADE_HOOKUP_OBJECT (gestion, label36, "label36");
  GLADE_HOOKUP_OBJECT (gestion, label19, "label19");
  GLADE_HOOKUP_OBJECT (gestion, label17, "label17");
  GLADE_HOOKUP_OBJECT (gestion, button4, "button4");
  GLADE_HOOKUP_OBJECT (gestion, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (gestion, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (gestion, image4, "image4");
  GLADE_HOOKUP_OBJECT (gestion, label21, "label21");
  GLADE_HOOKUP_OBJECT (gestion, label22, "label22");
  GLADE_HOOKUP_OBJECT (gestion, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (gestion, scrolledwindow2, "scrolledwindow2");
  GLADE_HOOKUP_OBJECT (gestion, treeview2, "treeview2");
  GLADE_HOOKUP_OBJECT (gestion, entry10, "entry10");
  GLADE_HOOKUP_OBJECT (gestion, bmodifier, "bmodifier");
  GLADE_HOOKUP_OBJECT (gestion, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (gestion, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (gestion, image14, "image14");
  GLADE_HOOKUP_OBJECT (gestion, label49, "label49");
  GLADE_HOOKUP_OBJECT (gestion, bafficher12, "bafficher12");
  GLADE_HOOKUP_OBJECT (gestion, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (gestion, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (gestion, image16, "image16");
  GLADE_HOOKUP_OBJECT (gestion, label51, "label51");
  GLADE_HOOKUP_OBJECT (gestion, label27, "label27");
  GLADE_HOOKUP_OBJECT (gestion, label26, "label26");
  GLADE_HOOKUP_OBJECT (gestion, bsupprimer, "bsupprimer");
  GLADE_HOOKUP_OBJECT (gestion, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (gestion, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (gestion, image15, "image15");
  GLADE_HOOKUP_OBJECT (gestion, label50, "label50");
  GLADE_HOOKUP_OBJECT (gestion, button6, "button6");
  GLADE_HOOKUP_OBJECT (gestion, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (gestion, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (gestion, image6, "image6");
  GLADE_HOOKUP_OBJECT (gestion, label30, "label30");
  GLADE_HOOKUP_OBJECT (gestion, label28, "label28");
  GLADE_HOOKUP_OBJECT (gestion, label29, "label29");
  GLADE_HOOKUP_OBJECT (gestion, label31, "label31");

  return gestion;
}

