/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_espace_capteur (void);
GtkWidget* create_gestion_capteur (void);
GtkWidget* create_ajouter_capteur (void);
GtkWidget* create_modifier_capteur (void);
GtkWidget* create_supprimer_capteur (void);
GtkWidget* create_enregistrement (void);
GtkWidget* create_ajouter_enregistrement (void);
GtkWidget* create_alarmante (void);
GtkWidget* create_marque_def (void);
