/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_espace_capteur (void)
{
  GtkWidget *espace_capteur;
  GtkWidget *fixed1;
  GtkWidget *gestion;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label1;
  GtkWidget *enreg;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label2;
  GtkWidget *bt_alarm;
  GtkWidget *bt_marque_def;

  espace_capteur = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (espace_capteur), _("Espace capteurs"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (espace_capteur), fixed1);

  gestion = gtk_button_new ();
  gtk_widget_show (gestion);
  gtk_fixed_put (GTK_FIXED (fixed1), gestion, 112, 72);
  gtk_widget_set_size_request (gestion, 190, 40);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (gestion), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-execute", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label1 = gtk_label_new_with_mnemonic (_(" Gestion des capteurs"));
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (hbox1), label1, FALSE, FALSE, 0);

  enreg = gtk_button_new ();
  gtk_widget_show (enreg);
  gtk_fixed_put (GTK_FIXED (fixed1), enreg, 112, 152);
  gtk_widget_set_size_request (enreg, 192, 40);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (enreg), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-media-play", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label2 = gtk_label_new_with_mnemonic (_(" Enregistrements"));
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (hbox2), label2, FALSE, FALSE, 0);

  bt_alarm = gtk_button_new_with_mnemonic (_("Capteurs Alarmants"));
  gtk_widget_show (bt_alarm);
  gtk_fixed_put (GTK_FIXED (fixed1), bt_alarm, 112, 224);
  gtk_widget_set_size_request (bt_alarm, 192, 40);

  bt_marque_def = gtk_button_new_with_mnemonic (_("Marque plus defectueux"));
  gtk_widget_show (bt_marque_def);
  gtk_fixed_put (GTK_FIXED (fixed1), bt_marque_def, 112, 288);
  gtk_widget_set_size_request (bt_marque_def, 192, 40);

  g_signal_connect ((gpointer) gestion, "clicked",
                    G_CALLBACK (on_gestion_clicked),
                    NULL);
  g_signal_connect ((gpointer) enreg, "clicked",
                    G_CALLBACK (on_enreg_clicked),
                    NULL);
  g_signal_connect ((gpointer) bt_alarm, "clicked",
                    G_CALLBACK (on_bt_alarm_clicked),
                    NULL);
  g_signal_connect ((gpointer) bt_marque_def, "clicked",
                    G_CALLBACK (on_bt_marque_def_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (espace_capteur, espace_capteur, "espace_capteur");
  GLADE_HOOKUP_OBJECT (espace_capteur, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (espace_capteur, gestion, "gestion");
  GLADE_HOOKUP_OBJECT (espace_capteur, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (espace_capteur, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (espace_capteur, image1, "image1");
  GLADE_HOOKUP_OBJECT (espace_capteur, label1, "label1");
  GLADE_HOOKUP_OBJECT (espace_capteur, enreg, "enreg");
  GLADE_HOOKUP_OBJECT (espace_capteur, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (espace_capteur, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (espace_capteur, image2, "image2");
  GLADE_HOOKUP_OBJECT (espace_capteur, label2, "label2");
  GLADE_HOOKUP_OBJECT (espace_capteur, bt_alarm, "bt_alarm");
  GLADE_HOOKUP_OBJECT (espace_capteur, bt_marque_def, "bt_marque_def");

  return espace_capteur;
}

GtkWidget*
create_gestion_capteur (void)
{
  GtkWidget *gestion_capteur;
  GtkWidget *fixed2;
  GtkWidget *treeview_capt;
  GtkWidget *ajouter_capt;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label3;
  GtkWidget *modifier_capt;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label4;
  GtkWidget *supprimer_capt;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label5;

  gestion_capteur = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (gestion_capteur), _("Gestion des Capteurs"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (gestion_capteur), fixed2);

  treeview_capt = gtk_tree_view_new ();
  gtk_widget_show (treeview_capt);
  gtk_fixed_put (GTK_FIXED (fixed2), treeview_capt, 80, 24);
  gtk_widget_set_size_request (treeview_capt, 500, 200);

  ajouter_capt = gtk_button_new ();
  gtk_widget_show (ajouter_capt);
  gtk_fixed_put (GTK_FIXED (fixed2), ajouter_capt, 32, 256);
  gtk_widget_set_size_request (ajouter_capt, 110, 40);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (ajouter_capt), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label3 = gtk_label_new_with_mnemonic (_(" Ajouter"));
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (hbox3), label3, FALSE, FALSE, 0);

  modifier_capt = gtk_button_new ();
  gtk_widget_show (modifier_capt);
  gtk_fixed_put (GTK_FIXED (fixed2), modifier_capt, 168, 256);
  gtk_widget_set_size_request (modifier_capt, 110, 40);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (modifier_capt), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label4 = gtk_label_new_with_mnemonic (_(" Modifier "));
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (hbox4), label4, FALSE, FALSE, 0);

  supprimer_capt = gtk_button_new ();
  gtk_widget_show (supprimer_capt);
  gtk_fixed_put (GTK_FIXED (fixed2), supprimer_capt, 312, 256);
  gtk_widget_set_size_request (supprimer_capt, 110, 40);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (supprimer_capt), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-remove", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label5 = gtk_label_new_with_mnemonic (_(" Supprimer"));
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox5), label5, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) treeview_capt, "row_activated",
                    G_CALLBACK (on_treeview_capt_row_activated),
                    NULL);
  g_signal_connect ((gpointer) ajouter_capt, "clicked",
                    G_CALLBACK (on_ajouter_capt_clicked),
                    NULL);
  g_signal_connect ((gpointer) modifier_capt, "clicked",
                    G_CALLBACK (on_modifier_capt_clicked),
                    NULL);
  g_signal_connect ((gpointer) supprimer_capt, "clicked",
                    G_CALLBACK (on_supprimer_capt_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (gestion_capteur, gestion_capteur, "gestion_capteur");
  GLADE_HOOKUP_OBJECT (gestion_capteur, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (gestion_capteur, treeview_capt, "treeview_capt");
  GLADE_HOOKUP_OBJECT (gestion_capteur, ajouter_capt, "ajouter_capt");
  GLADE_HOOKUP_OBJECT (gestion_capteur, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (gestion_capteur, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (gestion_capteur, image3, "image3");
  GLADE_HOOKUP_OBJECT (gestion_capteur, label3, "label3");
  GLADE_HOOKUP_OBJECT (gestion_capteur, modifier_capt, "modifier_capt");
  GLADE_HOOKUP_OBJECT (gestion_capteur, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (gestion_capteur, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (gestion_capteur, image4, "image4");
  GLADE_HOOKUP_OBJECT (gestion_capteur, label4, "label4");
  GLADE_HOOKUP_OBJECT (gestion_capteur, supprimer_capt, "supprimer_capt");
  GLADE_HOOKUP_OBJECT (gestion_capteur, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (gestion_capteur, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (gestion_capteur, image5, "image5");
  GLADE_HOOKUP_OBJECT (gestion_capteur, label5, "label5");

  return gestion_capteur;
}

GtkWidget*
create_ajouter_capteur (void)
{
  GtkWidget *ajouter_capteur;
  GtkWidget *fixed3;
  GtkWidget *entry_marque;
  GtkWidget *label7;
  GtkWidget *label6;
  GtkWidget *entry_mat;
  GtkWidget *label24;
  GtkWidget *Ajout_ok;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label8;
  GtkWidget *retour_ajout;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image11;
  GtkWidget *label25;
  GtkWidget *rb_ajout1;
  GSList *rb_ajout1_group = NULL;
  GtkWidget *rb_ajout2;

  ajouter_capteur = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ajouter_capteur), _("Ajouter Capteur"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (ajouter_capteur), fixed3);

  entry_marque = gtk_entry_new ();
  gtk_widget_show (entry_marque);
  gtk_fixed_put (GTK_FIXED (fixed3), entry_marque, 128, 104);
  gtk_widget_set_size_request (entry_marque, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_marque), 8226);

  label7 = gtk_label_new (_("Type : "));
  gtk_widget_show (label7);
  gtk_fixed_put (GTK_FIXED (fixed3), label7, 32, 160);
  gtk_widget_set_size_request (label7, 96, 41);

  label6 = gtk_label_new (_("Marque : "));
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed3), label6, 24, 104);
  gtk_widget_set_size_request (label6, 96, 33);

  entry_mat = gtk_entry_new ();
  gtk_widget_show (entry_mat);
  gtk_fixed_put (GTK_FIXED (fixed3), entry_mat, 128, 32);
  gtk_widget_set_size_request (entry_mat, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_mat), 8226);

  label24 = gtk_label_new (_("Matricule :"));
  gtk_widget_show (label24);
  gtk_fixed_put (GTK_FIXED (fixed3), label24, 24, 40);
  gtk_widget_set_size_request (label24, 81, 17);

  Ajout_ok = gtk_button_new ();
  gtk_widget_show (Ajout_ok);
  gtk_fixed_put (GTK_FIXED (fixed3), Ajout_ok, 96, 240);
  gtk_widget_set_size_request (Ajout_ok, 100, 40);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (Ajout_ok), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label8 = gtk_label_new_with_mnemonic (_(" OK"));
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (hbox6), label8, FALSE, FALSE, 0);

  retour_ajout = gtk_button_new ();
  gtk_widget_show (retour_ajout);
  gtk_fixed_put (GTK_FIXED (fixed3), retour_ajout, 240, 240);
  gtk_widget_set_size_request (retour_ajout, 96, 40);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (retour_ajout), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image11 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox11), image11, FALSE, FALSE, 0);

  label25 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label25);
  gtk_box_pack_start (GTK_BOX (hbox11), label25, FALSE, FALSE, 0);

  rb_ajout1 = gtk_radio_button_new_with_mnemonic (NULL, _("Temperature"));
  gtk_widget_show (rb_ajout1);
  gtk_fixed_put (GTK_FIXED (fixed3), rb_ajout1, 120, 168);
  gtk_widget_set_size_request (rb_ajout1, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (rb_ajout1), rb_ajout1_group);
  rb_ajout1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (rb_ajout1));

  rb_ajout2 = gtk_radio_button_new_with_mnemonic (NULL, _("Humidite"));
  gtk_widget_show (rb_ajout2);
  gtk_fixed_put (GTK_FIXED (fixed3), rb_ajout2, 256, 168);
  gtk_widget_set_size_request (rb_ajout2, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (rb_ajout2), rb_ajout1_group);
  rb_ajout1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (rb_ajout2));

  g_signal_connect ((gpointer) Ajout_ok, "clicked",
                    G_CALLBACK (on_Ajout_ok_clicked),
                    NULL);
  g_signal_connect ((gpointer) retour_ajout, "clicked",
                    G_CALLBACK (on_retour_ajout_clicked),
                    NULL);
  g_signal_connect ((gpointer) rb_ajout1, "toggled",
                    G_CALLBACK (on_rb_ajout1_toggled),
                    NULL);
  g_signal_connect ((gpointer) rb_ajout2, "toggled",
                    G_CALLBACK (on_rb_ajout2_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ajouter_capteur, ajouter_capteur, "ajouter_capteur");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, entry_marque, "entry_marque");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, label7, "label7");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, label6, "label6");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, entry_mat, "entry_mat");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, label24, "label24");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, Ajout_ok, "Ajout_ok");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, image6, "image6");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, label8, "label8");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, retour_ajout, "retour_ajout");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, image11, "image11");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, label25, "label25");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, rb_ajout1, "rb_ajout1");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, rb_ajout2, "rb_ajout2");

  return ajouter_capteur;
}

GtkWidget*
create_modifier_capteur (void)
{
  GtkWidget *modifier_capteur;
  GtkWidget *fixed4;
  GtkWidget *label9;
  GtkWidget *entry_marque_modif;
  GtkWidget *label10;
  GtkWidget *label11;
  GtkWidget *retour_modif;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image12;
  GtkWidget *label26;
  GtkWidget *cb_mat_modif;
  GtkWidget *modif_ok;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label13;
  GtkWidget *label12;
  GtkWidget *rb_modif1;
  GSList *rb_modif1_group = NULL;
  GtkWidget *rb_modif2;

  modifier_capteur = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (modifier_capteur), _("Modifier capteur"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (modifier_capteur), fixed4);

  label9 = gtk_label_new (_("Modifier un capteur : "));
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (fixed4), label9, 72, 16);
  gtk_widget_set_size_request (label9, 216, 49);

  entry_marque_modif = gtk_entry_new ();
  gtk_widget_show (entry_marque_modif);
  gtk_fixed_put (GTK_FIXED (fixed4), entry_marque_modif, 112, 168);
  gtk_widget_set_size_request (entry_marque_modif, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_marque_modif), 8226);

  label10 = gtk_label_new (_("Matricule : "));
  gtk_widget_show (label10);
  gtk_fixed_put (GTK_FIXED (fixed4), label10, 24, 96);
  gtk_widget_set_size_request (label10, 88, 33);

  label11 = gtk_label_new (_("Marque : "));
  gtk_widget_show (label11);
  gtk_fixed_put (GTK_FIXED (fixed4), label11, 32, 168);
  gtk_widget_set_size_request (label11, 80, 33);

  retour_modif = gtk_button_new ();
  gtk_widget_show (retour_modif);
  gtk_fixed_put (GTK_FIXED (fixed4), retour_modif, 184, 288);
  gtk_widget_set_size_request (retour_modif, 106, 37);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (retour_modif), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image12 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox12), image12, FALSE, FALSE, 0);

  label26 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label26);
  gtk_box_pack_start (GTK_BOX (hbox12), label26, FALSE, FALSE, 0);

  cb_mat_modif = gtk_combo_box_new_text ();
  gtk_widget_show (cb_mat_modif);
  gtk_fixed_put (GTK_FIXED (fixed4), cb_mat_modif, 120, 96);
  gtk_widget_set_size_request (cb_mat_modif, 136, 31);

  modif_ok = gtk_button_new ();
  gtk_widget_show (modif_ok);
  gtk_fixed_put (GTK_FIXED (fixed4), modif_ok, 56, 288);
  gtk_widget_set_size_request (modif_ok, 106, 37);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (modif_ok), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label13 = gtk_label_new_with_mnemonic (_("  OK"));
  gtk_widget_show (label13);
  gtk_box_pack_start (GTK_BOX (hbox7), label13, FALSE, FALSE, 0);

  label12 = gtk_label_new (_("Type : "));
  gtk_widget_show (label12);
  gtk_fixed_put (GTK_FIXED (fixed4), label12, 16, 232);
  gtk_widget_set_size_request (label12, 88, 25);

  rb_modif1 = gtk_radio_button_new_with_mnemonic (NULL, _("Temperature"));
  gtk_widget_show (rb_modif1);
  gtk_fixed_put (GTK_FIXED (fixed4), rb_modif1, 96, 232);
  gtk_widget_set_size_request (rb_modif1, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (rb_modif1), rb_modif1_group);
  rb_modif1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (rb_modif1));

  rb_modif2 = gtk_radio_button_new_with_mnemonic (NULL, _("Humidite"));
  gtk_widget_show (rb_modif2);
  gtk_fixed_put (GTK_FIXED (fixed4), rb_modif2, 232, 232);
  gtk_widget_set_size_request (rb_modif2, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (rb_modif2), rb_modif1_group);
  rb_modif1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (rb_modif2));

  g_signal_connect ((gpointer) retour_modif, "clicked",
                    G_CALLBACK (on_retour_modif_clicked),
                    NULL);
  g_signal_connect ((gpointer) modif_ok, "clicked",
                    G_CALLBACK (on_modif_ok_clicked),
                    NULL);
  g_signal_connect ((gpointer) rb_modif1, "toggled",
                    G_CALLBACK (on_rb_modif1_toggled),
                    NULL);
  g_signal_connect ((gpointer) rb_modif2, "toggled",
                    G_CALLBACK (on_rb_modif2_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (modifier_capteur, modifier_capteur, "modifier_capteur");
  GLADE_HOOKUP_OBJECT (modifier_capteur, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (modifier_capteur, label9, "label9");
  GLADE_HOOKUP_OBJECT (modifier_capteur, entry_marque_modif, "entry_marque_modif");
  GLADE_HOOKUP_OBJECT (modifier_capteur, label10, "label10");
  GLADE_HOOKUP_OBJECT (modifier_capteur, label11, "label11");
  GLADE_HOOKUP_OBJECT (modifier_capteur, retour_modif, "retour_modif");
  GLADE_HOOKUP_OBJECT (modifier_capteur, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (modifier_capteur, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (modifier_capteur, image12, "image12");
  GLADE_HOOKUP_OBJECT (modifier_capteur, label26, "label26");
  GLADE_HOOKUP_OBJECT (modifier_capteur, cb_mat_modif, "cb_mat_modif");
  GLADE_HOOKUP_OBJECT (modifier_capteur, modif_ok, "modif_ok");
  GLADE_HOOKUP_OBJECT (modifier_capteur, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (modifier_capteur, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (modifier_capteur, image7, "image7");
  GLADE_HOOKUP_OBJECT (modifier_capteur, label13, "label13");
  GLADE_HOOKUP_OBJECT (modifier_capteur, label12, "label12");
  GLADE_HOOKUP_OBJECT (modifier_capteur, rb_modif1, "rb_modif1");
  GLADE_HOOKUP_OBJECT (modifier_capteur, rb_modif2, "rb_modif2");

  return modifier_capteur;
}

GtkWidget*
create_supprimer_capteur (void)
{
  GtkWidget *supprimer_capteur;
  GtkWidget *fixed5;
  GtkWidget *combobox_supp;
  GtkWidget *supprim_ok;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label16;
  GtkWidget *retour_supp;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image13;
  GtkWidget *label27;
  GtkWidget *label14;
  GtkWidget *label15;

  supprimer_capteur = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (supprimer_capteur), _("Supprimer capteur "));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (supprimer_capteur), fixed5);

  combobox_supp = gtk_combo_box_new_text ();
  gtk_widget_show (combobox_supp);
  gtk_fixed_put (GTK_FIXED (fixed5), combobox_supp, 112, 88);
  gtk_widget_set_size_request (combobox_supp, 100, 31);

  supprim_ok = gtk_button_new ();
  gtk_widget_show (supprim_ok);
  gtk_fixed_put (GTK_FIXED (fixed5), supprim_ok, 56, 216);
  gtk_widget_set_size_request (supprim_ok, 96, 37);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (supprim_ok), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label16 = gtk_label_new_with_mnemonic (_(" OK"));
  gtk_widget_show (label16);
  gtk_box_pack_start (GTK_BOX (hbox8), label16, FALSE, FALSE, 0);

  retour_supp = gtk_button_new ();
  gtk_widget_show (retour_supp);
  gtk_fixed_put (GTK_FIXED (fixed5), retour_supp, 200, 216);
  gtk_widget_set_size_request (retour_supp, 90, 37);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (retour_supp), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image13 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox13), image13, FALSE, FALSE, 0);

  label27 = gtk_label_new_with_mnemonic (_(" Retour"));
  gtk_widget_show (label27);
  gtk_box_pack_start (GTK_BOX (hbox13), label27, FALSE, FALSE, 0);

  label14 = gtk_label_new (_("Supprimer un capteur :"));
  gtk_widget_show (label14);
  gtk_fixed_put (GTK_FIXED (fixed5), label14, 16, 16);
  gtk_widget_set_size_request (label14, 320, 57);

  label15 = gtk_label_new (_("Matricule : "));
  gtk_widget_show (label15);
  gtk_fixed_put (GTK_FIXED (fixed5), label15, 8, 88);
  gtk_widget_set_size_request (label15, 97, 25);

  g_signal_connect ((gpointer) supprim_ok, "clicked",
                    G_CALLBACK (on_supprim_ok_clicked),
                    NULL);
  g_signal_connect ((gpointer) retour_supp, "clicked",
                    G_CALLBACK (on_retour_supp_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (supprimer_capteur, supprimer_capteur, "supprimer_capteur");
  GLADE_HOOKUP_OBJECT (supprimer_capteur, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (supprimer_capteur, combobox_supp, "combobox_supp");
  GLADE_HOOKUP_OBJECT (supprimer_capteur, supprim_ok, "supprim_ok");
  GLADE_HOOKUP_OBJECT (supprimer_capteur, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (supprimer_capteur, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (supprimer_capteur, image8, "image8");
  GLADE_HOOKUP_OBJECT (supprimer_capteur, label16, "label16");
  GLADE_HOOKUP_OBJECT (supprimer_capteur, retour_supp, "retour_supp");
  GLADE_HOOKUP_OBJECT (supprimer_capteur, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (supprimer_capteur, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (supprimer_capteur, image13, "image13");
  GLADE_HOOKUP_OBJECT (supprimer_capteur, label27, "label27");
  GLADE_HOOKUP_OBJECT (supprimer_capteur, label14, "label14");
  GLADE_HOOKUP_OBJECT (supprimer_capteur, label15, "label15");

  return supprimer_capteur;
}

GtkWidget*
create_enregistrement (void)
{
  GtkWidget *enregistrement;
  GtkWidget *fixed6;
  GtkWidget *treeview_enreg;
  GtkWidget *label17;
  GtkWidget *ajout_enreg;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *label18;

  enregistrement = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (enregistrement), _("Enregistrement des capteurs "));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (enregistrement), fixed6);

  treeview_enreg = gtk_tree_view_new ();
  gtk_widget_show (treeview_enreg);
  gtk_fixed_put (GTK_FIXED (fixed6), treeview_enreg, 112, 64);
  gtk_widget_set_size_request (treeview_enreg, 300, 200);

  label17 = gtk_label_new (_("Enregistrement des capteurs :"));
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed6), label17, 128, 24);
  gtk_widget_set_size_request (label17, 240, 25);

  ajout_enreg = gtk_button_new ();
  gtk_widget_show (ajout_enreg);
  gtk_fixed_put (GTK_FIXED (fixed6), ajout_enreg, 264, 304);
  gtk_widget_set_size_request (ajout_enreg, 216, 37);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (ajout_enreg), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image9 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  label18 = gtk_label_new_with_mnemonic (_(" Ajouter un enregistrement "));
  gtk_widget_show (label18);
  gtk_box_pack_start (GTK_BOX (hbox9), label18, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) treeview_enreg, "row_activated",
                    G_CALLBACK (on_treeview_enreg_row_activated),
                    NULL);
  g_signal_connect ((gpointer) ajout_enreg, "clicked",
                    G_CALLBACK (on_ajout_enreg_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (enregistrement, enregistrement, "enregistrement");
  GLADE_HOOKUP_OBJECT (enregistrement, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (enregistrement, treeview_enreg, "treeview_enreg");
  GLADE_HOOKUP_OBJECT (enregistrement, label17, "label17");
  GLADE_HOOKUP_OBJECT (enregistrement, ajout_enreg, "ajout_enreg");
  GLADE_HOOKUP_OBJECT (enregistrement, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (enregistrement, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (enregistrement, image9, "image9");
  GLADE_HOOKUP_OBJECT (enregistrement, label18, "label18");

  return enregistrement;
}

GtkWidget*
create_ajouter_enregistrement (void)
{
  GtkWidget *ajouter_enregistrement;
  GtkWidget *fixed7;
  GtkWidget *label20;
  GtkWidget *label21;
  GtkWidget *label22;
  GtkObject *spinbutton_jour_adj;
  GtkWidget *spinbutton_jour;
  GtkObject *spinbutton_mois_adj;
  GtkWidget *spinbutton_mois;
  GtkObject *spinbutton_annee_adj;
  GtkWidget *spinbutton_annee;
  GtkObject *spinbutton_heure_adj;
  GtkWidget *spinbutton_heure;
  GtkObject *spinbutton_minute_adj;
  GtkWidget *spinbutton_minute;
  GtkWidget *entry_val;
  GtkWidget *cb_enreg;
  GtkWidget *enreg_ok;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image10;
  GtkWidget *label23;
  GtkWidget *retour_enreg;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image14;
  GtkWidget *label28;
  GtkWidget *label19;

  ajouter_enregistrement = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ajouter_enregistrement), _("Ajouter enregistrement"));

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (ajouter_enregistrement), fixed7);

  label20 = gtk_label_new (_("Date :"));
  gtk_widget_show (label20);
  gtk_fixed_put (GTK_FIXED (fixed7), label20, 24, 112);
  gtk_widget_set_size_request (label20, 80, 24);

  label21 = gtk_label_new (_("Heure : "));
  gtk_widget_show (label21);
  gtk_fixed_put (GTK_FIXED (fixed7), label21, 40, 168);
  gtk_widget_set_size_request (label21, 49, 17);

  label22 = gtk_label_new (_("Valeur : "));
  gtk_widget_show (label22);
  gtk_fixed_put (GTK_FIXED (fixed7), label22, 40, 224);
  gtk_widget_set_size_request (label22, 49, 17);

  spinbutton_jour_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton_jour = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_jour_adj), 1, 0);
  gtk_widget_show (spinbutton_jour);
  gtk_fixed_put (GTK_FIXED (fixed7), spinbutton_jour, 104, 112);
  gtk_widget_set_size_request (spinbutton_jour, 60, 27);

  spinbutton_mois_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton_mois = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_mois_adj), 1, 0);
  gtk_widget_show (spinbutton_mois);
  gtk_fixed_put (GTK_FIXED (fixed7), spinbutton_mois, 200, 112);
  gtk_widget_set_size_request (spinbutton_mois, 60, 27);

  spinbutton_annee_adj = gtk_adjustment_new (2020, 2020, 2030, 1, 10, 10);
  spinbutton_annee = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_annee_adj), 1, 0);
  gtk_widget_show (spinbutton_annee);
  gtk_fixed_put (GTK_FIXED (fixed7), spinbutton_annee, 296, 112);
  gtk_widget_set_size_request (spinbutton_annee, 60, 27);

  spinbutton_heure_adj = gtk_adjustment_new (0, 0, 23, 1, 10, 10);
  spinbutton_heure = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_heure_adj), 1, 0);
  gtk_widget_show (spinbutton_heure);
  gtk_fixed_put (GTK_FIXED (fixed7), spinbutton_heure, 104, 160);
  gtk_widget_set_size_request (spinbutton_heure, 60, 27);

  spinbutton_minute_adj = gtk_adjustment_new (0, 0, 59, 1, 10, 10);
  spinbutton_minute = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_minute_adj), 1, 0);
  gtk_widget_show (spinbutton_minute);
  gtk_fixed_put (GTK_FIXED (fixed7), spinbutton_minute, 200, 160);
  gtk_widget_set_size_request (spinbutton_minute, 60, 27);

  entry_val = gtk_entry_new ();
  gtk_widget_show (entry_val);
  gtk_fixed_put (GTK_FIXED (fixed7), entry_val, 104, 216);
  gtk_widget_set_size_request (entry_val, 70, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_val), 8226);

  cb_enreg = gtk_combo_box_new_text ();
  gtk_widget_show (cb_enreg);
  gtk_fixed_put (GTK_FIXED (fixed7), cb_enreg, 112, 56);
  gtk_widget_set_size_request (cb_enreg, 100, 31);

  enreg_ok = gtk_button_new ();
  gtk_widget_show (enreg_ok);
  gtk_fixed_put (GTK_FIXED (fixed7), enreg_ok, 128, 280);
  gtk_widget_set_size_request (enreg_ok, 90, 37);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (enreg_ok), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image10 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox10), image10, FALSE, FALSE, 0);

  label23 = gtk_label_new_with_mnemonic (_(" OK"));
  gtk_widget_show (label23);
  gtk_box_pack_start (GTK_BOX (hbox10), label23, FALSE, FALSE, 0);

  retour_enreg = gtk_button_new ();
  gtk_widget_show (retour_enreg);
  gtk_fixed_put (GTK_FIXED (fixed7), retour_enreg, 264, 280);
  gtk_widget_set_size_request (retour_enreg, 90, 37);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (retour_enreg), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image14 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox14), image14, FALSE, FALSE, 0);

  label28 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label28);
  gtk_box_pack_start (GTK_BOX (hbox14), label28, FALSE, FALSE, 0);

  label19 = gtk_label_new (_("Matricule :"));
  gtk_widget_show (label19);
  gtk_fixed_put (GTK_FIXED (fixed7), label19, 24, 56);
  gtk_widget_set_size_request (label19, 80, 25);

  g_signal_connect ((gpointer) enreg_ok, "clicked",
                    G_CALLBACK (on_enreg_ok_clicked),
                    NULL);
  g_signal_connect ((gpointer) retour_enreg, "clicked",
                    G_CALLBACK (on_retour_enreg_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ajouter_enregistrement, ajouter_enregistrement, "ajouter_enregistrement");
  GLADE_HOOKUP_OBJECT (ajouter_enregistrement, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (ajouter_enregistrement, label20, "label20");
  GLADE_HOOKUP_OBJECT (ajouter_enregistrement, label21, "label21");
  GLADE_HOOKUP_OBJECT (ajouter_enregistrement, label22, "label22");
  GLADE_HOOKUP_OBJECT (ajouter_enregistrement, spinbutton_jour, "spinbutton_jour");
  GLADE_HOOKUP_OBJECT (ajouter_enregistrement, spinbutton_mois, "spinbutton_mois");
  GLADE_HOOKUP_OBJECT (ajouter_enregistrement, spinbutton_annee, "spinbutton_annee");
  GLADE_HOOKUP_OBJECT (ajouter_enregistrement, spinbutton_heure, "spinbutton_heure");
  GLADE_HOOKUP_OBJECT (ajouter_enregistrement, spinbutton_minute, "spinbutton_minute");
  GLADE_HOOKUP_OBJECT (ajouter_enregistrement, entry_val, "entry_val");
  GLADE_HOOKUP_OBJECT (ajouter_enregistrement, cb_enreg, "cb_enreg");
  GLADE_HOOKUP_OBJECT (ajouter_enregistrement, enreg_ok, "enreg_ok");
  GLADE_HOOKUP_OBJECT (ajouter_enregistrement, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (ajouter_enregistrement, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (ajouter_enregistrement, image10, "image10");
  GLADE_HOOKUP_OBJECT (ajouter_enregistrement, label23, "label23");
  GLADE_HOOKUP_OBJECT (ajouter_enregistrement, retour_enreg, "retour_enreg");
  GLADE_HOOKUP_OBJECT (ajouter_enregistrement, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (ajouter_enregistrement, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (ajouter_enregistrement, image14, "image14");
  GLADE_HOOKUP_OBJECT (ajouter_enregistrement, label28, "label28");
  GLADE_HOOKUP_OBJECT (ajouter_enregistrement, label19, "label19");

  return ajouter_enregistrement;
}

GtkWidget*
create_alarmante (void)
{
  GtkWidget *alarmante;
  GtkWidget *fixed8;
  GtkWidget *treeview_alarm;
  GtkWidget *label29;

  alarmante = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (alarmante), _("Valeurs alarmantes"));

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (alarmante), fixed8);

  treeview_alarm = gtk_tree_view_new ();
  gtk_widget_show (treeview_alarm);
  gtk_fixed_put (GTK_FIXED (fixed8), treeview_alarm, 104, 88);
  gtk_widget_set_size_request (treeview_alarm, 300, 200);

  label29 = gtk_label_new (_("Les matricules des capteurs ayant des valeurs alarmantes :"));
  gtk_widget_show (label29);
  gtk_fixed_put (GTK_FIXED (fixed8), label29, 48, 24);
  gtk_widget_set_size_request (label29, 408, 40);

  g_signal_connect ((gpointer) treeview_alarm, "row_activated",
                    G_CALLBACK (on_treeview_alarm_row_activated),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (alarmante, alarmante, "alarmante");
  GLADE_HOOKUP_OBJECT (alarmante, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (alarmante, treeview_alarm, "treeview_alarm");
  GLADE_HOOKUP_OBJECT (alarmante, label29, "label29");

  return alarmante;
}

GtkWidget*
create_marque_def (void)
{
  GtkWidget *marque_def;
  GtkWidget *fixed9;
  GtkWidget *label30;
  GtkWidget *label_marque;

  marque_def = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (marque_def), _("marque plus defectueux"));

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_container_add (GTK_CONTAINER (marque_def), fixed9);

  label30 = gtk_label_new (_("La marque ayant le maximum des capteurs defectueux : "));
  gtk_widget_show (label30);
  gtk_fixed_put (GTK_FIXED (fixed9), label30, 16, 24);
  gtk_widget_set_size_request (label30, 376, 88);

  label_marque = gtk_label_new ("");
  gtk_widget_show (label_marque);
  gtk_fixed_put (GTK_FIXED (fixed9), label_marque, 80, 120);
  gtk_widget_set_size_request (label_marque, 216, 57);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (marque_def, marque_def, "marque_def");
  GLADE_HOOKUP_OBJECT (marque_def, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (marque_def, label30, "label30");
  GLADE_HOOKUP_OBJECT (marque_def, label_marque, "label_marque");

  return marque_def;
}

