/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Gestiondeplantation (void);
GtkWidget* create_Ajouter_plante (void);
GtkWidget* create_Modifier_plante (void);
GtkWidget* create_Supprimer_plante (void);
