/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Gestion_des_employes (void);
GtkWidget* create_ajouter_employes (void);
GtkWidget* create_modifier_employes (void);
GtkWidget* create_supprimer_employes (void);
