/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Gestion_des_clients (void);
GtkWidget* create_ajouter_clients (void);
GtkWidget* create_modifier_clients (void);
GtkWidget* create_supprimer_clients (void);
